title: Abigail Rieck # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Social science researcher and data analyst. BA with High Honors in Anthropology and minor in Applied Statistics from the University of Michigan. Previously at Alpine Archaeological Conultants, Inc.
  <br><br>
  Experienced with R, SQL, and GIS software. Fast learner with a passion for discovering how to answer unusual questions with a wide variety of data types.
  <br><br>
  <a href="www.linkedin.com/in/abigail-rieck-7626531b9">View My LinkedIn Profile</a> 

  
remote_theme: pages-themes/minimal@v0.2.0 
plugins:
- jekyll-remote-theme
